# Generated by Django 5.2.3 on 2025-06-12 14:56

import uuid
from django.db import migrations, models

def populate_uuids(apps, schema_editor):
    SKU = apps.get_model('api', 'SKU')
    for sku in SKU.objects.all():
        sku.uuid = uuid.uuid4()
        sku.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, default=None),
        ),
        migrations.RunPython(populate_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sku',
            name='uuid',
            field=models.UUIDField(null=False, unique=True, default=uuid.uuid4, editable=False),
        ),
    ]
