# Generated by Django 5.2.3 on 2025-06-12 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sku_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentscoreactivity',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
